version: '3'

services:
  nginx:
    image: nginx:1.23.3-alpine-slim
    volumes:
      - ./app:/var/www/html:z
      # - ./logs:/var/log/nginx:z
      - ./nginx/conf.d:/etc/nginx/conf.d/:z
    ports:
      - "80:80"
    tty:  true
    restart: unless-stopped
    container_name: nginx
    depends_on:
      - composer

  php74:
    image: php:7.4.33-fpm-alpine3.16
    ports:
      - "9000:9000"
    restart: unless-stopped
    user: 1000:1000
    container_name: php74
    volumes:
      - ./app:/var/www/html:z
      - ./php/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf:z

  composer:
      image: composer:2.0.8
      volumes:
        - ./app:/var/www/html:z
      user: 1000:1000
      working_dir: /var/www/html
      # Install laravel
      command: composer create-project laravel/laravel laravel
      # # Install composer
      # command: composer install
      # Update composer
      command: composer update
      container_name: composer
      depends_on:
        - php74